TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += sprlg.proto

DB_INSTALLS += base.template
DB_INSTALLS += channel.template

#=======================================
include $(TOP)/configure/RULES
