TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += sprlg_thermo.proto
DATA += sprlg_strain.proto

DB += superlogics.db 
DB += superlogics_thermo_channel.db
DB += superlogics_thermo_connected.db
DB += superlogics_strain_input.db

#=======================================
include $(TOP)/configure/RULES
