TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += sprlg.proto

DB += base.template channel.template

#=======================================
include $(TOP)/configure/RULES
